-------------------------------------------------------
-- Professional database design like Enterprise Grade.
-------------------------------------------------------
CREATE TABLE EMPLOYEE (
    EMP_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    FIRST_NAME  VARCHAR2(100) NOT NULL,
    LAST_NAME   VARCHAR2(100),
    EMAIL       VARCHAR2(100) NOT NULL,
    PHONE       VARCHAR2(20) NOT NULL,
    SALARY      NUMBER(10,2),
    DEPARTMENT  VARCHAR2(20),
    JOIN_DATE   DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_EMPLOYEE          PRIMARY KEY (EMP_ID),
    CONSTRAINT UK_EMPLOYEE_EMAIL    UNIQUE (EMAIL),
    CONSTRAINT UK_EMPLOYEE_PHONE    UNIQUE (PHONE)
);

-- SELECT TABLE_NAME FROM USER_TABLES;
-- INSERT INTO EMPLOYEE(EMP_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, SALARY, DEPARTMENT) VALUES
-- (1, 'Jakir', 'Ahmed', 'jakir@gmail.com', '01788916805', 85658, 'Finance'),
-- (2, 'Jasim', 'Uddin', 'jasim@gmail.com', '01785916801', 56866, 'Account'),
-- (3, 'Samim', 'Kamal', 'samim@gmail.com', '01788916545', 85648, 'Finance'),
-- (4, 'Kabir', 'Kajon', 'kabir@gmail.com', '01788943805', 85358, 'Finance'),
-- (5, 'Faruk', 'Hossain', 'faruk@gmail.com', '01788934805', 85653, 'Finance');

-- select * from employee;
