package com.jakirbd.ems.employee.dto;

import lombok.Builder;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDate;

@Data
@Builder

public class EmployeeResponse {
    private Long employeeId;
    private String firstName;
    private String lastName;
    private String email;
    private String phone;
    private BigDecimal salary;
    private String department;
    private LocalDate joinDate;
}

// Response DTO
// Contains what the server returns.

//{
//    "employeeId": 1,
//    "firstName": "Jakir",
//    "lastName": "Hasan",
//    "email": "jakir@gmail.com",
//    "phone": "01700000000",
//    "salary": 50000,
//    "department": "IT",
//    "joinDate": "2026-06-26"
//}

// This prevents clients from sending values like employeeId or joinDate that should be generated by the system.