CREATE TABLE EMPLOYEE (
    EMP_ID        NUMBER PRIMARY KEY,
    FIRST_NAME    VARCHAR2(50) NOT NULL,
    LAST_NAME     VARCHAR2(50),
    EMAIL         VARCHAR2(100) UNIQUE NOT NULL,
    PHONE         VARCHAR2(20) UNIQUE NOT NULL,
    SALARY        NUMBER(10,2),
    DEPARTMENT    VARCHAR2(50),
    JOIN_DATE     DATE DEFAULT SYSDATE
);