CREATE OR REPLACE PACKAGE EMPLOYEE_PKG AS

    -- CREATE
    PROCEDURE ADD_EMPLOYEE(
        P_FIRST_NAME  IN VARCHAR2,
        P_LAST_NAME   IN VARCHAR2,
        P_EMAIL       IN VARCHAR2,
        P_PHONE       IN VARCHAR2,
        P_SALARY      IN NUMBER,
        P_DEPARTMENT  IN VARCHAR2,
        P_EMP_ID      OUT NUMBER
    );

    -- READ BY ID
    PROCEDURE GET_EMPLOYEE_BY_ID(
        P_EMP_ID IN NUMBER,
        P_CURSOR OUT SYS_REFCURSOR
    );

    -- READ ALL
    PROCEDURE GET_ALL_EMPLOYEES(
        P_CURSOR OUT SYS_REFCURSOR
    );

    -- UPDATE
    PROCEDURE UPDATE_EMPLOYEE(
        P_EMP_ID      IN NUMBER,
        P_FIRST_NAME  IN VARCHAR2,
        P_LAST_NAME   IN VARCHAR2,
        P_EMAIL       IN VARCHAR2,
        P_PHONE       IN VARCHAR2,
        P_SALARY      IN NUMBER,
        P_DEPARTMENT  IN VARCHAR2
    );

    -- DELETE
    PROCEDURE DELETE_EMPLOYEE(
        P_EMP_ID IN NUMBER
    );

END EMPLOYEE_PKG;
/

CREATE OR REPLACE PACKAGE BODY EMPLOYEE_PKG AS

    -- CREATE EMPLOYEE
    PROCEDURE ADD_EMPLOYEE(
        P_FIRST_NAME  IN VARCHAR2,
        P_LAST_NAME   IN VARCHAR2,
        P_EMAIL       IN VARCHAR2,
        P_PHONE       IN VARCHAR2,
        P_SALARY      IN NUMBER,
        P_DEPARTMENT  IN VARCHAR2,
        P_EMP_ID      OUT NUMBER
    )
        IS
BEGIN
SELECT EMPLOYEE_SEQ.NEXTVAL INTO P_EMP_ID FROM DUAL;

INSERT INTO EMPLOYEE (
    EMP_ID, FIRST_NAME, LAST_NAME, EMAIL,
    PHONE, SALARY, DEPARTMENT, JOIN_DATE
)
VALUES (
           P_EMP_ID, P_FIRST_NAME, P_LAST_NAME, P_EMAIL,
           P_PHONE, P_SALARY, P_DEPARTMENT, SYSDATE
       );
END ADD_EMPLOYEE;


    -- GET BY ID
    PROCEDURE GET_EMPLOYEE_BY_ID(
        P_EMP_ID IN NUMBER,
        P_CURSOR OUT SYS_REFCURSOR
    )
IS
BEGIN
OPEN P_CURSOR FOR
SELECT * FROM EMPLOYEE WHERE EMP_ID = P_EMP_ID;
END GET_EMPLOYEE_BY_ID;


    -- GET ALL
    PROCEDURE GET_ALL_EMPLOYEES(
        P_CURSOR OUT SYS_REFCURSOR
    )
IS
BEGIN
OPEN P_CURSOR FOR
SELECT * FROM EMPLOYEE ORDER BY EMP_ID;
END GET_ALL_EMPLOYEES;


    -- UPDATE
    PROCEDURE UPDATE_EMPLOYEE(
        P_EMP_ID      IN NUMBER,
        P_FIRST_NAME  IN VARCHAR2,
        P_LAST_NAME   IN VARCHAR2,
        P_EMAIL       IN VARCHAR2,
        P_PHONE       IN VARCHAR2,
        P_SALARY      IN NUMBER,
        P_DEPARTMENT  IN VARCHAR2
    )
IS
BEGIN
UPDATE EMPLOYEE
SET FIRST_NAME = P_FIRST_NAME,
    LAST_NAME  = P_LAST_NAME,
    EMAIL      = P_EMAIL,
    PHONE      = P_PHONE,
    SALARY     = P_SALARY,
    DEPARTMENT = P_DEPARTMENT
WHERE EMP_ID = P_EMP_ID;
END UPDATE_EMPLOYEE;


    -- DELETE
    PROCEDURE DELETE_EMPLOYEE(
        P_EMP_ID IN NUMBER
    )
IS
BEGIN
DELETE FROM EMPLOYEE WHERE EMP_ID = P_EMP_ID;
END DELETE_EMPLOYEE;

END EMPLOYEE_PKG;
/